CREATE DATABASE TEST

USE TEST

CREATE TABLE NGANHHOC
(
	MaNganh CHAR(4) PRIMARY KEY,
	IsDeleted BOOLEAN DEFAULT FALSE,
	TenNganh NVARCHAR(30)

)

CREATE TABLE SINHVIEN(
	MaSV CHAR(10) PRIMARY KEY,
	HoTen NVARCHAR(50) NOT NULL,
	GioiTinh NVARCHAR(5),
	NgaySinh DATE,
	Hinh VARCHAR(50),
	IsDeleted BOOLEAN DEFAULT FALSE,
	MaNganh CHAR(4) REFERENCES NGANHHOC(MaNganh)
)

CREATE TABLE HOCPHAN
(
	MaHP CHAR(6) PRIMARY KEY,
	TenHP NVARCHAR(30) NOT NULL,
	IsDeleted BOOLEAN DEFAULT FALSE,
	SoTinChi INT
)

CREATE TABLE DANGKY(
	MaDK CHAR(36) PRIMARY KEY DEFAULT(UUID()),
	NgayDK DATE,
	IsDeleted BOOLEAN DEFAULT FALSE,
	MaSV CHAR(10) REFERENCES SINHVIEN(MaSV)
)

CREATE TABLE CHITIETDANGKY(
	MaDK CHAR(36) REFERENCES DANGKY(MaDK),
	MaHP CHAR(6) REFERENCES HOCPHAN(MaHP),
	IsDeleted BOOLEAN DEFAULT FALSE,
	PRIMARY KEY(MaDK,MaHP)
)

INSERT INTO NGANHHOC (MaNganh, TenNganh, IsDeleted) VALUES 
('CNTT', 'Công Nghệ Thông Tin', FALSE),
('QTKD', 'Quản Trị Kinh Doanh', FALSE)

INSERT INTO SINHVIEN (MaSV, HoTen, GioiTinh, NgaySinh, Hinh, IsDeleted, MaNganh) VALUES 
('2180607874', 'Nguyễn Văn Phong', 'Nam', '2003-03-03', '/content/images/nv-phong.jpg', FALSE, 'CNTT'),
('9876543210', 'Nguyễn Thị B', 'Nữ', '2000-07-03', '/content/images/sv2.jpg', FALSE, 'QTKD')

INSERT INTO HOCPHAN (MaHP, TenHP, IsDeleted, SoTinChi) VALUES 
('CNTT01', 'Lập Trình C', FALSE, 3),
('CNTT02', 'Cơ Sở Dữ Liệu', FALSE, 2),
('QTKD01', 'Kinh Tế Vi Mô', FALSE, 2),
('QTKD02', 'Xác Suất Thống Kê 1', FALSE, 3)

INSERT INTO DANGKY (NgayDK, IsDeleted, MaSV) VALUES 
('2024-03-24', FALSE, '2180607874'),
('2024-03-24', FALSE, '9876543210')

INSERT INTO CHITIETDANGKY (MaDK, MaHP, IsDeleted)
SELECT MaDK, 'CNTT01', FALSE FROM DANGKY WHERE MaSV = '2180607874'
UNION ALL
SELECT MaDK, 'CNTT02', FALSE FROM DANGKY WHERE MaSV = '2180607874'
UNION ALL
SELECT MaDK, 'QTKD01', FALSE FROM DANGKY WHERE MaSV = '9876543210'
UNION ALL
SELECT MaDK, 'QTKD02', FALSE FROM DANGKY WHERE MaSV = '9876543210'


SELECT * FROM SINHVIEN;
SELECT * FROM NGANHHOC;
SELECT * FROM HOCPHAN;
SELECT * FROM DANGKY;
SELECT * FROM CHITIETDANGKY;

ALTER TABLE HOCPHAN
ADD SoLuongDuKien INT DEFAULT 50;

-- Cập nhật dữ liệu mẫu cho cột SoLuongDuKien
UPDATE HOCPHAN 
SET SoLuongDuKien = CASE MaHP
	WHEN 'CNTT01' THEN 50
	WHEN 'CNTT02' THEN 40
	WHEN 'QTKD01' THEN 30
	WHEN 'QTKD02' THEN 20
END
WHERE MaHP IN ('CNTT01', 'CNTT02', 'QTKD01', 'QTKD02');
